# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

exclude: 'app/assets/scss/generic/**'

linters:
    CapitalizationInSelector:
        enabled: true
    ColorKeyword:
        enabled: false
    Comment:
        enabled: false
    DebugStatment:
        enabled: true
    DeclarationOrder:
        enabled: true
    DuplicateProperty:
        enabled: true
        exclude:
            - 'app/assets/scss/partials/_base.scss'
    EmptyLineBetweenBlocks:
        enabled: true
    EmptyRule:
        enabled: true
    FinalNewline:
        enabled: true
    HexLength:
        enabled: false
    HexNotation:
        enabled: true
        style: uppercase
    HexValidation:
        enable: true
    IdWithExtraneousSelector:
        enabled: true
    Indentation:
        enabled: true
        width: 4
    LeadingZero:
        enabled: true
        style: include_zero
    MergableSelector:
        enabled: true
        force_nesting: true
    NameFormat:
        enabled: true
    PlaceholderInExtend:
        enabled: true
    PropertySortOrder:
        enabled: false
    PropertySpelling:
        enabled: true
    SelectorDepth:
        enabled: true
        max_depth: 3
    Shorthand:
        enabled: true
    SingleLinePerSelector:
        enabled: true
        exclude:
            - 'app/assets/scss/partials/_base.scss'
    SpaceAfterComma:
        enabled: true
    SpaceAfterPropertyColon:
        enabled: true
    SpaceAfterPropertyName:
        enabled: true
    SpaceBeforeBrace:
        enabled: true
    SpaceBetweenParens:
        enabled: true
    StringQuotes:
        enabled: true
        style: double_quotes
    TrailingSemicolonAfterPropertyValue:
        enabled: true
    UnnecessaryMantissa:
        enabled: true
    UrlFormat:
        enabled: true
    UrlQuotes:
        enabled: true
    ZeroUnit:
        enabled: true