var universities = [
	"University of Aberdeen", 
	"University of Abertay, Dundee", 
	"Anglia Polytechnic University", 
	"Aston University", 
	"University of Bath", 
	"Bath Spa University College", 
	"Birkbeck College, University of London", 
	"University of Birmingham", 
	"University of Bournemouth", 
	"University of Bradford", 
	"University of Brighton", 
	"University of Bristol", 
	"Brunel University", 
	"University of Buckingham", 
	"University of Cambridge", 
	"Canterbury Christ Church University College", 
	"Chichester College", 
	"University of Central England", 
	"University of Central Lancashire", 
	"City University, London", 
	"University of Coventry", 
	"Cranfield University", 
	"University of Derby", 
	"University of Dundee", 
	"University of Durham", 
	"University of East Anglia", 
	"University of East London", 
	"University of Edinburgh", 
	"Edinburgh College of Art", 
	"University of Essex", 
	"University of Exeter", 
	"Glasgow Caledonian University", 
	"University of Glamorgan", 
	"University of Glasgow", 
	"Glasgow School of Art", 
	"University of Gloucestershire", 
	"University of Greenwich", 
	"University of London School of Pharmacy", 
	"London Guildhall University", 
	"London Metropolitan University", 
	"Harper-Adams Agricultural College", 
	"Heriot-Watt University", 
	"University of Hertfordshire", 
	"Homerton College Cambridge", 
	"University of Huddersfield", 
	"University of Hull", 
	"Institute of Cancer Research, University of London", 
	"Institute of Education, University of London", 
	"University of Keele", 
	"University of Kent at Canterbury", 
	"Kingston University", 
	"University of Lancaster", 
	"University of Leeds", 
	"Leeds Metropolitan University", 
	"University of Leicester", 
	"De Montfort University", 
	"University of Lincoln and Humberside", 
	"University of Liverpool", 
	"Liverpool John Moores University", 
	"Goldsmiths College, University of London", 
	"Imperial College, University of London", 
	"London University Business School", 
	"London Institute", 
	"King's College London", 
	"Queen Mary, University of London", 
	"Royal Holloway, University of London", 
	"University College London", 
	"London School of Hygiene and Tropical Medicine", 
	"London School of Economics", 
	"School of Oriental and African Studies", 
	"University of Loughborough", 
	"University of Luton", 
	"Manchester Metropolitan University", 
	"University of Manchester", 
	"University of Manchester Institute of Science and Technology", 
	"University of Middlesex", 
	"Napier University", 
	"University of Newcastle", 
	"University of Northumbria", 
	"University of North London", 
	"University of Wales College Newport", 
	"Northampton University College", 
	"University of Nottingham", 
	"Nottingham Trent University", 
	"University of the Arts London", 
	"Open University", 
	"University of Oxford", 
	"Oxford Brookes University", 
	"University of Paisley", 
	"University of Plymouth", 
	"University of Portsmouth", 
	"Queen Margaret University College", 
	"Queen's University Belfast", 
	"University of Reading", 
	"The Robert Gordon University", 
	"The Royal Vetinary College, University of London", 
	"The Royal College of Art", 
	"University of St Andrews", 
	"University of Salford", 
	"University of Sheffield", 
	"Sheffield Hallam University", 
	"University of Southampton", 
	"South Bank University", 
	"University of Staffordshire", 
	"University of Stirling", 
	"University of Strathclyde", 
	"University of Sunderland", 
	"The Surrey Institute of Art and Design University College", 
	"University of Surrey", 
	"University of Surrey, Roehampton", 
	"University of Sussex", 
	"St.George's Hospital Medical School", 
	"University of Teeside", 
	"Thames Valley University", 
	"University of Ulster", 
	"University of Wales, Aberystwyth", 
	"University of Wales Bangor", 
	"Cardiff University", 
	"University of Wales, Lampeter", 
	"University of Wales Swansea", 
	"University of Warwick", 
	"University of the West of England", 
	"University of Wales Institute at Cardiff", 
	"University of Westminster", 
	"University of Wolverhampton", 
	"University College Worcester", 
	"University of York"
]; 